FROM node:18 AS build

WORKDIR /app

COPY client/package*.json ./

RUN npm install

# Copy the rest of the application code to the container
COPY client/ .

RUN npm run build

# Stage 2: Serve the React application with Nginx
FROM nginx:alpine

# Copy the built React application from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000

CMD [ "nginx","-g","daemon off;" ]
